---
title: "exercises-rexex"
author: "John Little"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## From Exercise One
Find the  

1. Number of instances of *carrier*   
2. Number of instances of *Carrier*     
3. Number of instances of *carrier* regardless of case 
4. Number of instances where a four digit number (e.g. 1960) is at the end of a sentence denoted by a period  
5. Using the following regex `\b[A-Z]{2,3}\b` How accurate do you feel this pattern matches two and three letter abbreviations?  

### Answers

[Answers](answers.html) to questions on this page

## From Exercise Two

1. What does `honesty?` match?
    a. the word "honesty"  
    b. "honest" or "honesty"  
    c. the word "honest" at the end of a question with a "?" punctuation mark  
    d. all of the above  
    e. none of the above  
  
## From Exercise Three

1. Reformat the names in the following format:

> Last Name:  \<lastname\><br>
> \-\-\-\-\-\-\-First Name\<tab\>\<firstname\>

hints:  
new line = `\n`
tab = `\t`
      
For Example:  

> Last Name: Dixon    
> -------First Name &nbsp; Odetta  

## From Exercise Four

1. Is there a hashtag that begins with a year?  (e.g. 2016)
2. Is there a hashtag that begins with any year?  
3. What is the complete hashtag?

